USE [master]
GO

/****** Object:  Database [Posterr]    Script Date: 10/05/2022 17:01:10 ******/
CREATE DATABASE [Posterr]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Posterr', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Posterr.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Posterr_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Posterr_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Posterr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Posterr] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Posterr] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Posterr] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Posterr] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Posterr] SET ARITHABORT OFF 
GO

ALTER DATABASE [Posterr] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Posterr] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Posterr] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Posterr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Posterr] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Posterr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Posterr] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Posterr] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Posterr] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Posterr] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Posterr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Posterr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Posterr] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Posterr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Posterr] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Posterr] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Posterr] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Posterr] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Posterr] SET  MULTI_USER 
GO

ALTER DATABASE [Posterr] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Posterr] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Posterr] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Posterr] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Posterr] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Posterr] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Posterr] SET  READ_WRITE 
GO


